# App Info
ios_app_id                                :                                          # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Wright                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The AI Writing app. Write, Generate, Answer question, Summarize and more.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Hand Made with ♥ by Suvi                                
your_link                                 :                
your_city                                 : Chennai                    
email_address                             : mail@example.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : vigneshghub
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Magical summary Generation
    description                           : Designed for generating summary, Just upload file or insert text, Voilá!
    fontawesome_icon_name                 : magic
    
  - title                                 : Quality Check
    description                           : Analyses the quality of your work and provides where improvement can be made.
    fontawesome_icon_name                 : award

  - title                                 : Read out
    description                           : After the generation, you could choose the read option to read the text to listen on the fly.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Sync with Drive, Dropbox.
    description                           : You can choose the app to directly sync the document with drive, dropbox.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : You can choose from a variety of report generation styles and one style can be converted to other.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Star User Rewards
    description                           : Use our app often ? Become Star user, share our app with your friends and get rewards.
    fontawesome_icon_name                 : star

  - title                                 : Instant Download 
    description                           : Instant Download to PDF, Docx and more
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : With one click, you could share your report to across all your social media account.
    fontawesome_icon_name                 : link

  - title                                 : Support
    description                           : Any problem, no worries. Get any help with your report within in 36 hours.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#1d63ea"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed
